### ISSUE TITLE
client should just have an option to build from an http.Client

### ISSUE THREAD

**Issue by james-lawrence** [go-openapi/runtime#19]
```go
type Runtime struct {
	DefaultMediaType      string
	DefaultAuthentication runtime.ClientAuthInfoWriter
	Consumers             map[string]runtime.Consumer
	Producers             map[string]runtime.Producer

	Transport http.RoundTripper
	Jar       http.CookieJar
	//Spec      *spec.Document
	Host     string
	BasePath string
	Formats  strfmt.Registry
	Debug    bool
	Context  context.Context

	clientOnce *sync.Once
	client     *http.Client
	schemes    []string
}
```

is harder to actually use than it needs to be. It takes a bunch of parameters to setup the http.Client meaning users have to jump through hoops to use it.

For example the authentication mechanism, we already have a great way for creating oauth2 clients in the
oauth2 library and creating a working http.Client. Instead of just creating the http.Client from there and
configuring the timeout as I desire I have to contort into go-openapi's model which in the end just creates an
http.Client anyways....

following fields could be stripped if http.Client was just accepted:
- Transport http.RoundTripper
- Jar http.CookieJar
- DefaultAuthentication runtime.ClientAuthInfoWriter (this is really just a Transport.)
- clientOnce *sync.Once

end result: could simplify the usage of the runtime client and provide helper methods for doing all the things that are currently being done.

**Comment by casualjim** [comment]
I've left Transport and Jar in for backwards compatibility, but you can use NewWithClient to create a http transport that uses your client instead, in that case the Jar and Transport methods are ignored. 

Both the ClientRequestWriter and ClientAuthInfoWriter are basically just RoundTripper middleware (`func(http.RoundTripper) http.RoundTripper)`, but that would be a very big change, 

I want to postpone this because I need to provide a second implementation for that one as I don't know who has or what has been built on top of these interfaces and I don't want to break the world.

**Comment by james-lawrence** [comment]
Yup thats effectively what I did in my own code. I copied the current implementation and ripped out the parts that were uncessary.
