### ISSUE TITLE
Support vendoring of referenced libraries

### ISSUE THREAD

**Issue by pazderak** [go-openapi/runtime#23]
What should be useful is to use packages on which runtime package depends as vendored code. I would like to use glide as package manager.

**Comment by GlenDC** [comment]
[go-swagger](https://github.com/go-swagger/go-swagger) uses [gvt](https://github.com/FiloSottile/gvt). Which also puts its dependencies under the `vendor` directory.

I don't think libraries of [go-openapi](https://github.com/go-openapi) have a `vendor` folder.

@casualjim  is probably in a better position to explain why.

**Comment by casualjim** [comment]
libraries shouldn't have a vendor folder, they should always work against masters of the libaries they depend on.
Go itself can't deal with nested vendors, so if we vendor in runtime then we're effectively making it impossible for other people to vendor runtime. Not every vendoring tool properly flattens vendored packages. 

The best we can do is a pre-check in the generator to let you know that certain dependencies are missing.
This is captured in this issue: https://github.com/go-swagger/go-swagger/issues/817

Where the more advanced version of this is: https://github.com/go-swagger/go-swagger/issues/818
but not sure how that can be solved until we have a standard package manager so that there is a standard format to parse and use for version checks
