### ISSUE TITLE
Explicit dependencies in vendor tree

### ISSUE THREAD

**Issue by fredbi** [go-openapi/runtime#71]
It would be nice to explicit the dependencies of this package in a vendor tree, so one can build our generated code without the go-swagger package itself.

**Comment by casualjim** [comment]
you just need to vendor github.com/go-openapi/runtime yourself. Depending on which tool you use to manager your vendor it hopefully brings in all the transient dependencies too.
The code generator prints which packages you require.

**Comment by fredbi** [comment]
Thanks. Sure I can imagine I can do that myself... This is what I did anyhow.
 
Just thought it would be NICE (not a bug), and favour somehow adoption of the right tool (who said dependencies management in go was simple to understand?). For real bugs, I'd rather post them to the main go-swagger package.

**Comment by casualjim** [comment]
I try to make swagger a tool that holds almost no opinion on how you should structure your work. At the same time until there is a clear winner in the vendoring tool space I don't want swagger to hold an opinion either. 
At this moment glide has more adoption than dep but going forward dep is supposed to win because it's almost like glide 2.0.

Feel free to submit issues on the go-swagger/go-swagger repo because that's the one that's being looked at the most.

**Comment by fredbi** [comment]
OK good point. I rest my case :).
See you on go-swagger/go-swagger then...
